### ISSUE TITLE
[Version 17 Shark Upgrade] AuthenticateMessageParams and CreateMinerParams don't implement interface cbor.Er

### ISSUE THREAD

**Issue by XianLeiGirl** [filecoin-project/go-state-types#106]
go-state-types v0.9.1
struct AuthenticateMessageParams and CreateMinerParams don't implement interface cbor.Er, which is not friendly for data parsing

**Comment by Stebalien** [comment]
Fixed in https://github.com/filecoin-project/go-state-types/pull/107, you can use that branch till someone wakes up to review it.
