### ISSUE TITLE
Migration bug: verifreg needs datacap for allocations

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-state-types#109]
@Kubuxu found this error upon ProveCommit while doing gas estimation.

```
01: f06 (method 9) -- failed to send burn BurnParams { amount: TokenAmount(34359738368.0) } to datacap: send to f07 method 19 aborted with code 19 (19)
02: f07 (method 19) -- state transaction failed: error in underlying state negative balance caused by decreasing 6's balance of TokenAmount(0.0) by TokenAmount(-34359738368.0) (19)
```

This would be explained by verifrege having insufficient datacap to account for its existing allocations.  Looking at the migration the datacap actor is missing a balance for verifreg.  This should be fixed.

**Comment by jennijuju** [comment]
fixed!
