### ISSUE TITLE
[Version 17 Shark Upgrade] the param of method UniversalReceiverHook doesn't implement  cbor.Er

### ISSUE THREAD

**Issue by XianLeiGirl** [filecoin-project/go-state-types#113]
go-state-types: v0.9.8
The params of UniversalReceiverHook for account and multisig should implement the interface cbor.Er instead of *[]byte type. The unified format facilitates data parsing.

**Comment by geoff-vball** [comment]
Closed by https://github.com/filecoin-project/go-state-types/pull/119
