### ISSUE TITLE
Maintenance: write down how to add placeholder for support of a new version of actors

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-state-types#122]
vyzo struggled a lot here https://github.com/filecoin-project/go-state-types/pull/90

@arajasek suggested he could really write down the general approach here, right now it's living in a few people's heads
(for the record i do agree with the decision of keeping files for each actor version instead of using aliasing  - this would be important for lotus, especially when we wanna drop support for certain historical actors)

so lets do that to make contribution to gst easier for folks in the future!

**Comment by jennijuju** [comment]
@arajasek is this something we can ask ian to develop a gh action for and automates it?

**Comment by rjan90** [comment]
@rjan90 To update GST-documentation to be in line with this doc: https://github.com/filecoin-project/lotus/blob/master/documentation/misc/Building_a_network_skeleton.md#go-state-types-checklist

**Comment by rjan90** [comment]
Create a pointer to Lotus-docs, so we keep the maintenence burden low
