### ISSUE TITLE
FIP-0047: Migration

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/go-state-types#123]
- Each `SectorOnChainInfo` needs a `ProofExpiration` epoch. It should be set as follows: 

> During migration at network upgrade, each sector’s ProofExpiration is set to that value it would have if it had initially been set to SectorActiviation + MaxProofDuration and then refreshed until the proof expiration is no less than the commitment expiration.

- Each Partition's `ExpirationSet` needs a new field `FaultySectors` which will contain the bitfield of sectors  expiring "early" due to being faulty for too long (previous this was in `EarlySectors`). `EarlySectors` will now contain the bitfield of sectors expiring "early" due to proof expiration. This should be set to an empty bitfield for the migration.

**Comment by jennijuju** [comment]
@Kubuxu could you please review and confirm all migration is captured?

**Comment by Kubuxu** [comment]
Sounds right

**Comment by ZenGround0** [comment]
Prolly close: https://github.com/filecoin-project/FIPs/discussions/415#discussioncomment-5173038

**Comment by rjan90** [comment]
Closing, since it has been superseded by FIP-0067
