### ISSUE TITLE
Migrate actors to v5

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-state-types#127]

**Comment by geoff-vball** [comment]
ActorV5 is already implemented in `actor_tree.go`. We just need to calculate and store the predictable address for any actors that we want to migrate. 

@Stebalien can probably define what actor types need to be migrated here.

**Comment by Stebalien** [comment]
The answer is "none". We've decided to not store _any_ predictable addresses, only f4 addresses. I'm currently updating FIP0048 to include this (instead of writing an entirely new FIP).

**Comment by Stebalien** [comment]
See https://github.com/filecoin-project/ref-fvm/pull/1290.
