### ISSUE TITLE
Add/check methods for Init, EVM, EAM, and ethaccount actors

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/go-state-types#132]
We need to make sure this repo fully aligns with the changes introduced to the v10 actors in the various FIPs landing in the nv18 upgrade. We know that we have:

- Four new actors: the EAM, EVM, EthAccount, and Placeholder actors
- State changes to the init actor 
- New methods on many of the actors (see FIP-0050).

- We should confirm that the method lists in `builtin/methods.go` and the individual `methods.go` files are correct wrt the actual actors in builtin-actors.
- We should confirm that for each of these methods, the method types (both input params and return) are correctly captured here.
- We should confirm that the new actors are correctly represented here in terms of both the methods and state types.
- (optional) We should do a sanity check over all existing actors as well, and confirm that their state and method types are correct.

**Comment by snissn** [comment]
below are snippets from my notes that had potential issues, chat tomorrow through them @arajasek !
 
for evm ConstructorParams we can change the eth address type to [20]byte from []byte or possibly use an even more specific type

type ConstructorParams struct {
  Creator  []byte // XXX should be eth address? or is bytes ok? // XXX how about [20]byte or created a type
  Initcode []byte
}


XXX do we want to enforce length 32 as the return type in go
evm     4       GetBytecodeHash func(*abi.EmptyValue) *abi.CborBytes
pub struct BytecodeHash(#[serde(with = "strict_bytes")] [u8; 32]);
    pub fn bytecode_hash(rt: &mut impl Runtime) -> Result<BytecodeHash, ActorError> {


evm     5       GetStorageAt    func(*evm.GetStorageAtParams) *abi.CborBytes
XXX looks like U256 vs []byte
pub struct GetStorageAtParams {
    pub storage_key: U256,
}
type GetStorageAtParams struct {
  StorageKey []byte
}  

ethaccount      3726118371      UniversalReceiverHook   func(*abi.CborBytesTransparent) *abi.EmptyValue
//XXX doesn't exist in rust but exists in go - easy to remove

**Comment by jennijuju** [comment]
can we close this now?

**Comment by rjan90** [comment]
Closing! If we ever want to do some of this, we will open another issue.
