### ISSUE TITLE
big: refactor Int type to not panic on json unmarshal

### ISSUE THREAD

**Issue by mvdan** [filecoin-project/go-state-types#14]
The type is currently:

```
type Int struct {
	*big.Int
}
```

Unfortunately, this results in a panic when unmarshaling JSON: https://play.golang.org/p/1q4SGAx7jug

The reason is that `Int` has an `UnmarshalText` method promoted from the embedded `*big.Int` field, so then `encoding/json` calls the method on the zero value of `Int`, which has a nil `*big.Int` field. We then call `UnmarshalText` on the nil `*big.Int`, which panics, because it expects the receiver to be non-nil.

This is to be expected, really. If a type implements unmarshal interfaces, they should work on its zero value, because otherwise they aren't actually useful. They would only be useful if the code first constructed the values before passing them onto `json.Unmarshal`, but that's pretty non-standard.

I assume that the current struct type is this way because you wanted your own type separate from `big.Int`, and you still wanted to have the same methods as a `big.Int`. It seems like you have multiple ways to fix this problem, from least to most amount of work:

1) Remove the pointer from the field, like `type Int struct{ big.Int }`. Should require no other code changes. The only pitfall is that `NewFromGo` would now copy the passed `*big.Int`, so the two wouldn't share the same memory.

2) Use a type alias, like `type Int = *big.Int`, making the two types equal. Constructors would become simpler, like `func NewFromGo(i *big.Int) Int { return i }`.

3) Use `big.Int` directly, removing your own type completely. Similar to option 2, but it would break the API, since users would need to switch to using `math/big` directly.

I think options 3 is the best long-term, but perhaps there's a reason you decoupled from `math/big` that I don't know. If that's not an option, then I would go for option 2, which shouldn't break any users as long as they were using the constructor funcs.

cc @magik6k @whyrusleeping @Kubuxu @anorth

**Comment by mvdan** [comment]
It seems like my reproducer above is a bit unfair to the existing type, because the existing type does implement its own `UnmarshalJSON` method. It's unclear why the original code caused a panic; the custom `UnmarshalJSON` method was never called from what one can see in the panic stack trace.

**Comment by Kubuxu** [comment]
Seems to work if I implement the UnmarshalJSON: https://play.golang.org/p/allvL5brBpa

**Comment by mvdan** [comment]
I spoke to soon here. There might be a Go spec bug here; I'll follow up shortly. Please ignore this thread meanwhile.

**Comment by mvdan** [comment]
Upstream bug filed: https://github.com/golang/go/issues/41685

**Comment by ribasushi** [comment]
@mvdan has this been resolved as a "go bug" / resoled in new versions of go ( which we should mandate ) or is this still n outstanding issue ( which we could cover in https://github.com/filecoin-project/go-state-types/pull/29 ) ?

**Comment by mvdan** [comment]
There's no resolution or fix upstream per se - the spec is technically working as documented. The only changes upstream might do are a [blog post](https://github.com/golang/go/issues/41685#issuecomment-700318832) to warn about this edge case, and a [vet check](https://github.com/golang/go/issues/41685#issuecomment-701459509) to warn about some very-likely-wrong scenarios.

Filecoin definitely needs its own fix to this issue. My original post in this thread is wrong in a way, because we do declare our own UnmarshalJSON method on the wrapping Int type. But, as the upstream bug demonstrates via https://play.golang.org/p/-FkcWvJzLZS, if you add another level of named types, then we "skip" over our UnmarshalJSON, and end up calling the inner MarshalJSON - hence the panic.

I still believe that, long-term, it would be best to either avoid our own "big int" wrapper type, or to at least not embed the underlying type, to avoid footguns like this one. If neither of those are possible changes in the short term, then I think something like #29 is more reasonable, to at least avoid the panics.

**Comment by mvdan** [comment]
As a longer explanation on what's going on in the example at https://play.golang.org/p/-FkcWvJzLZS.

--

There are two spec definitions at play here:

A) when you embed a named type, its methods get "promoted" to the parent. there are some exception rules here, but none apply for the example.

B) when you declare a new named type, it begins with an empty method set.

So, what happens in the example is, in order:

1) `big.Int` has an `UnmarshalJSON` method.
2) `Embedding` is a named type that embeds `big.Int`. It starts with an empty method set, and gets `UnmarshalJSON` promoted from the struct embedding.
3) `Embedding` declares an `UnmarshalJSON` method, which shadows/overrides the promoted method.

So far so good. `Embedding` works; if we json decode, it uses our own `UnmarshalJSON` method.

4) `NewNamed` is a named type like `type NewNamed Embedding`. It shares the same *underlying* type, meaning `struct { *big.Int }`.
5) As before, `NewNamed` begins with an empty method set. Due to the same underlying type, it gets the promoted `UnmarshalJSON` from `big.Int`.
6) NewNamed does not get any other method. It certainly does not get `Embedding.UnmarshalJSON`, which is causing the Filecoin panic.

So then, when you json decode into `NewNamed,` it panics, because we end up skipping over our `UnmarshalJSON`, and going for the promoted one from math/big, which does a nil deref panic.
