### ISSUE TITLE
Update the state invariants for FEVM actors

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-state-types#144]
We need to add invariants for the new FEVM actors, so that we can perform sanity checks on state. See the [multisig invariants](https://github.com/filecoin-project/go-state-types/blob/3ee9fb7d0a8254ad98bbdebca7b005f077701dbe/builtin/v10/multisig/invariants.go#L19) for a simple example of what these invariants look like.

A non-exhaustive list of assertions to make includes:
- Embryo actors should always have the ["empty object"](https://github.com/filecoin-project/go-state-types/blob/890a3642f2cbd8fee141f682d17f74db1e8abf7e/builtin/v10/migration/top.go#L354-L361) as their state (I'd consider making this a defined constant in GST if possible)
- EthAccounts should also always have the empty object as their state
- EAM should also always have the empty object as their state
- EVM actors: TODO
- Init actor: Anything new to add?

**Comment by arajasek** [comment]
For the init actor, we should assert that for every f4 address in its address_map, if we look up the [Actor](https://github.com/filecoin-project/lotus/blob/674d12770194011e1cd9c8166fd1e5631ccfa0fb/chain/types/actor.go#L30) corresponding to it in the state tree, that actor has its (optional) `Address` field correctly set to the same f4 Address.
