### ISSUE TITLE
Remove methods from RegisteredXxxProof types

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-state-types#18]
Methods on these integers are handy, but they complicate making any structural changes without integrating those changes into _every_ actors release branch. E.g. we will probably want to remove `RegisteredSealProof.RegisteredWindowPoStProof()` because there's no necessary bijection there, but all call sites in all actors release branches need to handle that.

If such methods were free functions, we'd have more flexibility to change without forcing lots of work or a major version upgrade of this repo.

**Comment by jennijuju** [comment]
is this still needed?

**Comment by anorth** [comment]
We still should do it IMO, but its importance depends on the versioning strategy for this repo. I'll defer to whoever has the vision for that @arajasek ?

**Comment by rjan90** [comment]
@anorth Is this worth keeping open, if so what are the AI we should take to implement this?

**Comment by rjan90** [comment]
Closing for now, unless you have strong objections Alex, feel free to re-open.
