### ISSUE TITLE
When the record upgraded to the `V1_1PostProof `, it's hard to find the corresponding SealProof Or downgraded PoStProof?

### ISSUE THREAD

**Issue by free1139** [filecoin-project/go-state-types#187]
https://github.com/filecoin-project/go-state-types/blob/1e6cf0d47cdda75383ef036fc2725d1cf51dbde8/abi/sector.go#L110

**Comment by rjan90** [comment]
Closing as we are realistically not have time to documenting this mapping at the current time.
