### ISSUE TITLE
Wrong type of SectorAllocationClaim in Verifiedregistry

### ISSUE THREAD

**Issue by Terryhung** [filecoin-project/go-state-types#241]
There is a discrepancy between the schema [SectorAllocationClaim](https://github.com/filecoin-project/builtin-actors/blob/master/actors/verifreg/src/types.rs#L137) in `builtin-actors v12` and the schema [SectorAllocationClaim](https://github.com/filecoin-project/go-state-types/blob/master/builtin/v12/verifreg/verifreg_types.go#L106) in `go-state-types v12`.

Therefore, there is a mismatch between the `SectorAllocationClaim` in `go-state-types` v12 and the actual data.

The new schema should be this:
```
pub struct SectorAllocationClaims {
    pub sector: SectorNumber,
    pub expiry: ChainEpoch,
    pub claims: Vec<AllocationClaim>,
}
```

Then I found it did not be fixed in v13, is there any plan for fix it?

Thanks!

**Comment by Stebalien** [comment]
If you make a PR, I'll review it.

**Comment by LuisCherry** [comment]
Excuse me, may I ask when this issue can be fixed

**Comment by rvagg** [comment]
to be fair to OP, changing these while making cbor-gen happy in the interim isn't exactly easy, here's a fix: https://github.com/filecoin-project/go-state-types/pull/262
