### ISSUE TITLE
Release for FIP-0090/0092

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/go-state-types#272]
Tracking issue for doing a Go-State-Types release for FIP-0090/0092 in support of nv23.

This will follow this process: https://github.com/filecoin-project/go-state-types/pull/273

```[tasklist]
### Depends on
- [ ] https://github.com/filecoin-project/go-state-types/pull/270
- [ ] https://github.com/filecoin-project/go-state-types/pull/269
```

**Comment by rjan90** [comment]
Notes for cutting a release in Go-State-Types:

- Go to https://github.com/filecoin-project/go-state-types/releases
- Click the `Draft a new release` button in right corner.
- In the `Choose a tag` dropdown, enter the desired version and click "Create new tag: vX.XX.X on publish"
- Target the master branch.
- Set previous tag to compare against, the last stable release, and click the `Generate release notes` button
- Check the `Set as a pre-release` if its a release candidate that is being cut, or check the `Set as the latests release` if its a stable release that is being cut.

**Comment by BigLep** [comment]
I'm marking this as closed since the release was done and since the release process was documented in https://github.com/filecoin-project/go-state-types/pull/273
